[package]
name = "ims-rs"
version = "0.5.0"
authors = ["Eugene Vert"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
rayon = "1.5"

csv = "1.1"
image = "0.23"
imageproc = "0.22"
img_hash = "3.2.0"
serde = "1.0"
serde_json = "1.0"
tempfile = "3.2"
zip = "0.5"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
