[package]
name = "imagescripts-rs"
version = "0.1.0"
authors = ["Eugene Vert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
structopt = "0.3"

rayon = "1.5"
tempfile = "3"

image = "0.23"
csv = "1.1"
serde_json = "1.0"
zip = "0.5"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
