[package]
name = "find"
version = "0.1.0"
authors = ["Eugene Vert"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
clap = "2"

[lib]
name = "bpp"
path = "bpp.rs"
